#!/bin/sh

DOTFILEDIR=.dotfiles
DIR=$HOME/$DOTFILEDIR

# ---------------------------------------------
# BASH
# ---------------------------------------------
echo "Linking Bash files"
ln -s  $DIR/bash/bash_profile  $HOME/.bash_profile
ln -s  $DIR/bash/bashrc        $HOME/.bashrc


# ---------------------------------------------
# GIT
# ---------------------------------------------
echo "Linking Git files ..."
ln -s  $DIR/git/gitconfig  $HOME/.gitconfig

# ---------------------------------------------
# VIM
# ---------------------------------------------
echo "Linking Vim files ..."
ln -s  $DIR/vim        $HOME/.vim
ln -s  $DIR/vim/vimrc  $HOME/.vimrc

if [ -d $DIR/vim/bundle/vundle ]; then
    echo "Vundle detected ..."
else
    echo "Installing vundle ..."
    git clone https://github.com/gmarik/vundle.git $DIR/vim/bundle/vundle
fi

vim +Bundleinstall +qall

